/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as SseHostsRouteImport } from './routes/sse/hosts'
import { Route as SseDecisionsRouteImport } from './routes/sse/decisions'
import { Route as AppUsersRouteImport } from './routes/_app/users'
import { Route as AppHostsRouteImport } from './routes/_app/hosts'
import { Route as AppDecisionsRouteImport } from './routes/_app/decisions'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const SseHostsRoute = SseHostsRouteImport.update({
  id: '/sse/hosts',
  path: '/sse/hosts',
  getParentRoute: () => rootRouteImport,
} as any)
const SseDecisionsRoute = SseDecisionsRouteImport.update({
  id: '/sse/decisions',
  path: '/sse/decisions',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppHostsRoute = AppHostsRouteImport.update({
  id: '/hosts',
  path: '/hosts',
  getParentRoute: () => AppRoute,
} as any)
const AppDecisionsRoute = AppDecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/decisions': typeof AppDecisionsRoute
  '/hosts': typeof AppHostsRoute
  '/users': typeof AppUsersRoute
  '/sse/decisions': typeof SseDecisionsRoute
  '/sse/hosts': typeof SseHostsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/decisions': typeof AppDecisionsRoute
  '/hosts': typeof AppHostsRoute
  '/users': typeof AppUsersRoute
  '/sse/decisions': typeof SseDecisionsRoute
  '/sse/hosts': typeof SseHostsRoute
  '/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/decisions': typeof AppDecisionsRoute
  '/_app/hosts': typeof AppHostsRoute
  '/_app/users': typeof AppUsersRoute
  '/sse/decisions': typeof SseDecisionsRoute
  '/sse/hosts': typeof SseHostsRoute
  '/_app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/decisions'
    | '/hosts'
    | '/users'
    | '/sse/decisions'
    | '/sse/hosts'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/decisions'
    | '/hosts'
    | '/users'
    | '/sse/decisions'
    | '/sse/hosts'
    | '/'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/decisions'
    | '/_app/hosts'
    | '/_app/users'
    | '/sse/decisions'
    | '/sse/hosts'
    | '/_app/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SseDecisionsRoute: typeof SseDecisionsRoute
  SseHostsRoute: typeof SseHostsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/sse/hosts': {
      id: '/sse/hosts'
      path: '/sse/hosts'
      fullPath: '/sse/hosts'
      preLoaderRoute: typeof SseHostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sse/decisions': {
      id: '/sse/decisions'
      path: '/sse/decisions'
      fullPath: '/sse/decisions'
      preLoaderRoute: typeof SseDecisionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hosts': {
      id: '/_app/hosts'
      path: '/hosts'
      fullPath: '/hosts'
      preLoaderRoute: typeof AppHostsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/decisions': {
      id: '/_app/decisions'
      path: '/decisions'
      fullPath: '/decisions'
      preLoaderRoute: typeof AppDecisionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppDecisionsRoute: typeof AppDecisionsRoute
  AppHostsRoute: typeof AppHostsRoute
  AppUsersRoute: typeof AppUsersRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDecisionsRoute: AppDecisionsRoute,
  AppHostsRoute: AppHostsRoute,
  AppUsersRoute: AppUsersRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SseDecisionsRoute: SseDecisionsRoute,
  SseHostsRoute: SseHostsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
